language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t docker-demo-react -f Dockerfile.dev .

script:
  - docker run -e CI=true docker-demo-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-demo-react"
  env: "DockerDemoReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-998054812439"
  bucket_path: "docker-demo-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
